# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for
fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier
transforms, basic linear algebra, basic statistical operations, random simulation and much more.

# what is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
## initialize numpy
import numpy as np

In [ ]:
!pip install numpy

In [3]:
lst = [1,2,3,4]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4])

shape of array

In [6]:
arr.shape

(4,)

# Multidimensional Array

In [7]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst3 = [7,8,9,10]
new_arr = np.array([lst1,lst2,lst3])

In [8]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])

In [10]:
new_arr.shape

(3, 4)

In [16]:
new_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 7,  8],
       [ 9, 10]])

In [4]:
import numpy as np
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst3 = [7,8,9,10]
new_arr = np.array([lst1,lst2,lst3])

In [5]:
new_arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  7],
       [ 8,  9, 10]])

# Indexing

In [6]:
# Accessing the array elements
arr = np.array([1,2,3,4,5,6,7,8,9])

In [8]:
arr[3:6]

array([4, 5, 6])

In [9]:
arr[-1]

9

In [10]:
arr[-2:]

array([8, 9])

In [20]:
arr[4]

5

In [11]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])

In [12]:
new_arr[1:,1:3]

array([[6, 7],
       [8, 9]])

In [23]:
new_arr[1:,2:]

array([[ 7,  8],
       [ 9, 10]])

In [24]:
new_arr[1,1]

6

In [25]:
new_arr[2,3]

10

In [26]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(0,10,3)
arr

array([0, 3, 6, 9])

In [15]:
arr = np.linspace(20,40,10)
arr

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

In [16]:
# copy function 
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[3:] = 20

In [18]:
arr

array([ 1,  2,  3, 20, 20, 20, 20, 20, 20])

In [19]:
arr1 = arr

In [20]:
arr1

array([ 1,  2,  3, 20, 20, 20, 20, 20, 20])

In [21]:
arr1[3:] = 30

In [22]:
arr1

array([ 1,  2,  3, 30, 30, 30, 30, 30, 30])

In [23]:
arr

array([ 1,  2,  3, 30, 30, 30, 30, 30, 30])

In [41]:
# copy
arr1 = arr.copy()

In [44]:
arr1[3:] = 50
print(arr1)
print(arr)

[ 1  2  3 50 50 50 50 50 50]
[ 1  2  3 30 30 30 30 30 30]


In [46]:
# zeros
arr1 = np.zeros((4,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# ones
arr2 = np.ones((3,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
# useful condition used in exploratory analysis

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [59]:
arr[arr<5]

array([1, 2, 3, 4])

In [60]:
# random distribution
np.random.rand(3,3)

array([[0.39399053, 0.90274768, 0.45356156],
       [0.58616914, 0.6040921 , 0.50342178],
       [0.60091162, 0.96644575, 0.72841774]])

In [61]:
np.random.randn(4,4)

array([[ 0.95185566,  0.24068955,  0.17620971,  0.69825379],
       [-0.06016999, -0.95036334,  1.36179933,  0.10657005],
       [ 2.12683451,  1.13569913,  1.35204781,  0.79657594],
       [ 0.41194629, -0.96333926, -0.25622053, -1.38993726]])

In [62]:
np.random.randint(0,100,8).reshape(4,2)


array([[78, 51],
       [49, 53],
       [91, 27],
       [76, 70]])